### ISSUE TITLE
Not passing req around (question)

### ISSUE THREAD

**Issue by avnersorek** [pvenkatakrishnan/flogger-sample#1]
Hi 

I saw that in your talk (https://vimeo.com/125005227) you mention the need of logging the request ID without passing `req` around (or down) to your services.
Here I see that you still have the need to pass it - you are just passing the logger instead (the activity service `getAll` method takes a `logger` parameter).

Do you think there is anyway around this - without passing the logger to the service in every call ?

Thanks

**Comment by pvenkatakrishnan** [comment]
In the example i think those 2 cases are orthogonal.
- The way you get away with passing req is providing a hook to the logger module in a middleware, which will have reference to the `req` in its closure. So it is indeed not passed around. Check https://github.com/pvenkatakrishnan/flogger-sample/blob/master/middlewares/loggerSetup.js#L4-L6
- Passing around a logger instance is slightly different. Here is the catch. The logger instance is unique to every request coz 
  1. each service call will have its own unique req params to get logged. 
  2. the logger should not grow in memory and get cleaned up when a `req` is done. 

Considering both the above requirements, the logger ends up getting a first class citizen treatment like any query params that will be passed around for service calls.

Now considering your request, if you don't want to deal with passing around loggers, it will probably end up like a singleton logHelper provided by `flogger` say on `require`, where logger instances get stashed into it when each `req` comes in through a middleware. But lets assume service calls have no access to req and does not have a logger passed in, you will `require` the loggerHelper but  service call has no way of figuring out which logger instance corresponds to the current `req`. Then the service call will need some unique Id  that will help it identify a logger to a `req`.
I did grapple with this as well for a little bit before i decided to go the current route.

**Comment by pvenkatakrishnan** [comment]
if you'd like the service call interfaces to have lesser arguments, perhaps you can design such that logger can be stashed into the params object passed to your service call :) although i would keep them separate as they mean distinct things to be acted on within the service call.

**Comment by avnersorek** [comment]
:+1: Thanks
I have to admit I'm not totally content with any of these approaches, as I feel they kind of dirty up the code and cross separation of concerns (IMHO).
But they are only a part of a bigger issue regarding the lack of isolated request context in node.
This was pretty easy to do with Domains but those are on their way out.

Thanks for your help anyway, I really enjoyed your lecture.

**Comment by avnersorek** [comment]
BTW -
Having 'transparent' access to the request id (or any other request context data),
Can be achieved without domains - possibly using [continuation-local-storage](https://www.npmjs.com/package/continuation-local-storage) and further described in [this blog post](https://datahero.com/blog/2014/05/22/node-js-preserving-data-across-async-callbacks/).

**Comment by pvenkatakrishnan** [comment]
ok cls comes with its own set of woes as you get deeper into it :) just a warning. especially when you mix it up with event emitters ...

**Comment by pvenkatakrishnan** [comment]
and pls do share back your findings when you have your ideal solution ! i'm always ready to learn about new ideas!

**Comment by avnersorek** [comment]
Will do. Probably won't be with cls though - as you said - it comes with some baggage ...
